baseurl = "https://f3l1x.io/"
languageCode = "en-us"
title = "Milan Felix Šulc - engineering for living"
enableGitInfo = false
disableKinds = ["taxonomyTerm", "taxonomy"]
disableHugoGeneratorInject = true
enableEmoji = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]

[outputFormats]
	[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			autoHeadingIDType = "github"
		[markup.goldmark.renderer]
			unsafe= true

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[params]
	github = "https://github.com/f3l1x/f3l1x/"
	github_content = "https://github.com/f3l1x/f3l1x/blob/master/content/"
	title_postfix = "Milan Felix Šulc"
	description = "I am Milan Šulc and I engineering for living."
	keywords = "milan šulc, f3l1x, developer, php, nette, java, javascript, typescript, rust, go"
	twitterEmoji=true
